In [1]:
import pandas as pd 
import numpy as np
import scipy.stats as st
import matplotlib.pyplot as plt


In [2]:
from sklearn.model_selection import train_test_split

In [3]:
class DetectorAnomalias():
    
    def __init__(self, epsilon):
        self.epsilon = epsilon
        
    def fit(self, X):
        medias = X.mean(axis = 0)
        desvios = X.std(axis = 0)
        gaussianas = [st.norm(loc = m, scale = d) for m, d in zip(medias, desvios)]  
        self.gaussianas = gaussianas
        self.X = X
        
    def prob(self, x):
        p = 1
        for i in range(self.X.shape[1]):
            gaussiana_i = self.gaussianas[i]
            x_i = x[i]
            p *= gaussiana_i.pdf(x_i)
        return p
    
    def isAnomaly(self, x):
        return int(np.where(self.prob(x) < self.epsilon, 1, 0))

In [4]:
def getData():
    return pd.read_csv("dataframe_anomalias_exercicio.csv")

In [5]:
df = getData()
df

,x1,x2,x3,x4,x5,x6,anomalia
0,7.731153,23.299155,-0.367453,4.715372,9.306179,16.780965,0.0
1,11.466833,16.943695,-0.245131,7.060311,10.462826,19.821289,0.0
2,11.501272,20.196011,1.206049,-4.957189,7.771262,19.100079,0.0
3,10.893921,16.072385,2.738045,-3.684228,7.373334,23.225524,0.0
4,10.091706,19.253894,0.996895,-9.504052,8.883988,17.903298,0.0
...,...,...,...,...,...,...,...
10095,11.192286,18.451987,-0.953650,-14.362996,10.875826,17.056541,0.0
10096,12.014177,19.461815,1.985099,-7.119190,11.079922,17.582755,0.0
10097,10.745460,18.175951,0.206037,-1.897015,9.888329,17.963324,0.0
10098,9.893969,22.333270,-1.465981,4.137382,7.690620,21.570097,0.0


In [6]:
dfA = df[df.anomalia == 1]

In [7]:
[dfA1,dfA2] = train_test_split(dfA,test_size=0.5)

In [8]:
dfB = df[df.anomalia == 0]

In [9]:
[dfB1,dfB2] = train_test_split(dfB,test_size=0.4)

In [10]:
dfB1.shape

(6027, 7)

In [11]:
dfB2.shape

(4019, 7)

In [12]:
[dfB1_,dfB2_] = train_test_split(dfB2,test_size=0.5)

In [13]:
print(df.shape,"df")
print(dfA.shape,"dfA")
print(dfA1.shape,"dfA1")
print(dfA2.shape,"dfA2")
print(dfB.shape,"dfB")
print(dfB1.shape,"dfB1")
print(dfB1_.shape,"dfB1_")
print(dfB2.shape,"dfB2")
print(dfB2_.shape,"dfB2_")


(10100, 7) df
(54, 7) dfA
(27, 7) dfA1
(27, 7) dfA2
(10046, 7) dfB
(6027, 7) dfB1
(2009, 7) dfB1_
(4019, 7) dfB2
(2010, 7) dfB2_


In [14]:
dftrain = dfB1
df_val = pd.concat([dfA1,dfB1_])
dftest = pd.concat([dfA2,dfB2_])

In [15]:
print(dftrain.anomalia.value_counts())
print(df_val.anomalia.value_counts())
print(dftest.anomalia.value_counts())

0.0    6027
Name: anomalia, dtype: int64
0.0    2009
1.0      27
Name: anomalia, dtype: int64
0.0    2010
1.0      27
Name: anomalia, dtype: int64


In [16]:
dfA.anomalia.value_counts()

1.0    54
Name: anomalia, dtype: int64

In [17]:
dfB.anomalia.value_counts()

0.0    10046
Name: anomalia, dtype: int64

In [18]:
X = dfA.values

In [19]:
X = X[:,:6]

In [20]:
ann = DetectorAnomalias(epsilon= 0.001)
ann.fit(X)

In [21]:
x = X[1,]
x

array([  6.43336027,  17.08111739,   1.50247431, -13.40364574,
        12.69444533,  23.09335712])

In [22]:
ann.prob(x)

7.236488489957413e-08

In [23]:
ann.isAnomaly(x)

1

In [24]:
X_ = dfB.values

In [25]:
X_.shape

(10046, 7)

In [26]:
X_ = X_[:,:6]
X_


array([[ 7.73115287, 23.29915461, -0.36745342,  4.71537151,  9.30617937,
        16.78096518],
       [11.46683276, 16.94369515, -0.24513144,  7.06031139, 10.46282586,
        19.82128898],
       [11.50127248, 20.19601072,  1.20604852, -4.95718899,  7.77126188,
        19.10007872],
       ...,
       [10.74546004, 18.17595064,  0.20603678, -1.89701473,  9.88832862,
        17.96332423],
       [ 9.8939691 , 22.3332699 , -1.46598096,  4.13738208,  7.69061987,
        21.57009704],
       [11.56324575, 20.77712125, -1.14531676, -4.65051456, 11.85762183,
        19.42488056]])

In [27]:
ann = DetectorAnomalias(epsilon= 0.0000001)
ann.fit(X_)

In [28]:
x = X_[0,]
x

array([ 7.73115287, 23.29915461, -0.36745342,  4.71537151,  9.30617937,
       16.78096518])

In [29]:
ann.prob(x)

4.090915261341661e-07

In [30]:
ann.isAnomaly(x)

0

In [31]:
ann = DetectorAnomalias(epsilon= 0.0000001)
ann.fit(X)

In [32]:
x = X[0,]
x

array([14.80391535, 18.79012675, -1.30187946, 11.96613235,  9.36580691,
       24.51271095])

In [33]:
ann.prob(x)

8.428760351765615e-08

In [34]:
ann.isAnomaly(x)

1

In [35]:
X = dftrain.values
X = X[:,:6]
X

array([[10.48844487, 20.54485783,  0.38713666,  6.06446734,  8.33782333,
        17.17879913],
       [11.10482241, 22.30236665, -0.83123651, -4.03116842,  7.59860625,
        20.64786211],
       [ 8.56561585, 18.92619477, -0.9872    ,  2.42948175,  8.91587826,
        21.69251408],
       ...,
       [14.0154983 , 22.22087289, -2.59002121, -7.40539838,  8.02186934,
        19.41206775],
       [ 9.78771142, 20.50495548,  0.73962895,  1.84029575,  8.76554352,
        23.39778072],
       [ 9.19815625, 19.58325302,  0.68612186, -0.49188079,  9.00098583,
        21.36780852]])

In [36]:
print("dftrain")
print(dftrain.anomalia.value_counts())
print("**********")
print("df_val")
print(df_val.anomalia.value_counts())
print("**********")
print("dftest")
print(dftest.anomalia.value_counts())

dftrain
0.0    6027
Name: anomalia, dtype: int64
**********
df_val
0.0    2009
1.0      27
Name: anomalia, dtype: int64
**********
dftest
0.0    2010
1.0      27
Name: anomalia, dtype: int64


In [37]:
X = dftrain.values
X = X[:,:6]
y = np.arange(0, 6027 , 1)
lista_de_anomaly = []
for a in y:
    ann = DetectorAnomalias(epsilon= 0.00000001)
    ann.fit(X)
    x = X[a,]
    lista_de_anomaly.append(ann.isAnomaly(x))

In [38]:
dftrain_fit = pd.DataFrame(lista_de_anomaly,columns=["dftrain_fit"])

In [39]:
dftrain_fit.dftrain_fit.value_counts()

0    6021
1       6
Name: dftrain_fit, dtype: int64

In [40]:
df_val.shape

(2036, 7)

In [41]:
X = df_val.values
X = X[:,:6]
y = np.arange(0, 2036 , 1)
lista_de_anomaly = []
for a in y:
    ann = DetectorAnomalias(epsilon= 0.00000001)
    ann.fit(X)
    x = X[a,]
    lista_de_anomaly.append(ann.isAnomaly(x))

In [42]:
df_val_fit = pd.DataFrame(lista_de_anomaly,columns=["df_val_fit"])

In [43]:
df_val_fit.df_val_fit.value_counts()

0    2008
1      28
Name: df_val_fit, dtype: int64

In [44]:
dftest.shape

(2037, 7)

In [45]:
X = dftest.values
X = X[:,:6]
y = np.arange(0, 2037 , 1)
lista_de_anomaly = []
for a in y:
    ann = DetectorAnomalias(epsilon= 0.00000001)
    ann.fit(X)
    x = X[a,]
    lista_de_anomaly.append(ann.isAnomaly(x))

In [46]:
dftest_fit = pd.DataFrame(lista_de_anomaly,columns=["dftest_fit"])

In [47]:
dftest_fit.dftest_fit.value_counts()

0    2011
1      26
Name: dftest_fit, dtype: int64

In [48]:
dftest.anomalia.value_counts()

0.0    2010
1.0      27
Name: anomalia, dtype: int64

In [49]:
df.shape

(10100, 7)

In [50]:
X = df.values
X = X[:,:6]
y = np.arange(0, 10100 , 1)
lista_de_anomaly = []
for a in y:
    ann = DetectorAnomalias(epsilon= 0.00000001)
    ann.fit(X)
    x = X[a,]
    lista_de_anomaly.append(ann.isAnomaly(x))

In [51]:
df_anomalia= pd.DataFrame(lista_de_anomaly,columns=["df_anomalia"])

In [52]:
df_anomalia.df_anomalia.value_counts()

0    10038
1       62
Name: df_anomalia, dtype: int64

In [53]:
df.anomalia.value_counts()

0.0    10046
1.0       54
Name: anomalia, dtype: int64

ate qui fiz a divisão dos dados, nao  sei se fiz da forma mais facil, mas deu certo, então rodei um loop variado o tamando do epsilon e criando um Datafreme para compara com o Datafreme original e ver se aproxima os valores , e este valor de epsilon foi oque mais se aproximou 

In [54]:
ann = DetectorAnomalias(epsilon= 0.00000001)

In [55]:
from sklearn.metrics import confusion_matrix

In [56]:
from sklearn.metrics import f1_score

In [57]:
from sklearn.metrics import accuracy_score

In [58]:
from sklearn.metrics import roc_auc_score

In [59]:
dftrain.shape

(6027, 7)

In [60]:
b = dftrain.values
b = b[:,:6]
y = np.arange(0, 6027 , 1)
X = []
for a in y:
    ann = DetectorAnomalias(epsilon= 0.00000001)
    ann.fit(b)
    x = b[a,]
    X.append(ann.isAnomaly(x))

In [61]:
from sklearn.linear_model import LogisticRegression
logreg = LogisticRegression()

In [62]:
logreg.fit(dftrain,X)

LogisticRegression()

In [63]:
confusion_matrix(y_true=X,y_pred= logreg.predict(dftrain))

array([[6021,    0],
       [   6,    0]], dtype=int64)

In [64]:
f1_score(y_true=X,y_pred= logreg.predict(dftrain))

0.0

In [65]:
logreg.predict(dftrain)[:100]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [66]:
accuracy_score(y_true = X, y_pred = logreg.predict(dftrain))

0.9990044798407167

In [67]:
b = df_val.values
b = b[:,:6]
y = np.arange(0, 2036 , 1)
X = []
for a in y:
    ann = DetectorAnomalias(epsilon= 0.00000001)
    ann.fit(b)
    x = b[a,]
    X.append(ann.isAnomaly(x))

In [68]:
logreg.fit(df_val,X)

LogisticRegression()

In [69]:
confusion_matrix(y_true=X,y_pred= logreg.predict(df_val))

array([[2008,    0],
       [   1,   27]], dtype=int64)

In [70]:
accuracy_score(y_true = X, y_pred = logreg.predict(df_val))

0.99950884086444

In [71]:
f1_score(y_true=X,y_pred= logreg.predict(df_val))

0.9818181818181818

In [73]:
b = df.values
b = b[:,:6]
y = np.arange(0, 10100 , 1)
X = []
for a in y:
    ann = DetectorAnomalias(epsilon= 0.00000001)
    ann.fit(b)
    x = b[a,]
    X.append(ann.isAnomaly(x))

In [74]:
logreg.fit(df,X)

LogisticRegression()

In [75]:
confusion_matrix(y_true=X,y_pred= logreg.predict(df))

array([[10038,     0],
       [    8,    54]], dtype=int64)

In [76]:
accuracy_score(y_true = X, y_pred = logreg.predict(df))

0.9992079207920792

In [77]:
f1_score(y_true=X,y_pred= logreg.predict(df))

0.9310344827586207

olhando para os dois resultados vejo bastante semelhança, vejo que o valor de epsilon que usei para da fit nos dados foi o melhor possivel , e olhando para confuconfusion_matrix que o codigo acertou bastante 